{application,cryptex,
             [{description,"An Elixir library for encrypting/decrypting, signing/verifying data.\n"},
              {modules,['Elixir.Cryptex','Elixir.Cryptex.KeyGenerator',
                        'Elixir.Cryptex.MessageEncryptor',
                        'Elixir.Cryptex.MessageVerifier',
                        'Elixir.Cryptex.Serializer',
                        'Elixir.Cryptex.Serializers.ELIXIR',
                        'Elixir.Cryptex.Serializers.NULL']},
              {registered,[]},
              {vsn,"0.0.1"},
              {applications,[kernel,stdlib,elixir]}]}.
