defmodule Mnemonic do
  @moduledoc """
  Module for generating a mnemonic phrase following the BIP0039 standard
  """
  alias GenerateIndexes

  @doc """
  Parses the file that cointains all the words used for generating a phrase
  """
  def get_wordlist() do
    {:ok, words} = File.read "priv/wordlist.txt"
    String.replace(words, "\n", ",") |> String.split(",") |> List.to_tuple()
  end

  @doc """
  Generates a phrase from a given list of indexes generated by the GenerateIndexes module
  """
  def generate_phrase(indexes) do
    phrase = ""
    phrase = for n <- indexes do
      phrase <> elem(get_wordlist(),n) <> " "
    end
    phrase |> List.to_string() |> String.trim()
  end

end
