defmodule Mnemonic do
  @moduledoc """
  Module for generating a mnemonic phrase following the BIP0039 standard
  """
  alias GenerateIndexes

  @doc """
  Generates a phrase from a given list of indexes
  generated by the GenerateIndexes module, where each index
  represents a word from the wordlist.txt file
  ## Examples
      iex> Mnemonic.generate_phrase([1223, 32, 453])
      "ocean advice december"
  """
  def generate_phrase(indexes) do
    phrase = ""
    for index <- indexes do
      phrase <> elem(get_wordlist(), index) <> " "
    end
    |> List.to_string()
    |> String.trim()
  end

  defp get_wordlist() do
    {:ok, words} = File.read "priv/wordlist.txt"
    String.replace(words, "\n", ",")
    |> String.split(",")
    |> List.to_tuple()
  end

end
